version: '3.4'

services:
  mercure:
    image: dunglas/mercure
    environment:
      - JWT_KEY='!ChangeMe!'
      - ALLOW_ANONYMOUS=1
      - CORS_ALLOWED_ORIGINS=*
      - PUBLISH_ALLOWED_ORIGINS=*
      - DEMO=1
    ports:
      - "3000:81"
